-- =============================================================================
-- Migration 010: Weekly packs system
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: weekly_packs
-- One row per team per week per league. Generated by the server cron.
-- Cards are stored as JSONB so the browser can render without extra queries.
-- ---------------------------------------------------------------------------
CREATE TABLE public.weekly_packs (
  id                       UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  league_id                UUID NOT NULL REFERENCES public.leagues(id)        ON DELETE CASCADE,
  season_id                UUID NOT NULL REFERENCES public.app_seasons(id)    ON DELETE CASCADE,
  user_id                  UUID NOT NULL,
  week                     INTEGER NOT NULL,
  pack_type                TEXT NOT NULL CHECK (pack_type  IN ('win','loss','normal')),
  odds_type                TEXT NOT NULL CHECK (odds_type  IN ('win','loss','normal')),
  cards                    JSONB NOT NULL DEFAULT '[]',
  selected_player_id       UUID REFERENCES public.players(id),
  selected_player_season_id UUID REFERENCES public.player_seasons(id),
  status                   TEXT NOT NULL DEFAULT 'pending'
                             CHECK (status IN ('pending','opened','forfeited')),
  available_from           TIMESTAMPTZ NOT NULL,
  expires_at               TIMESTAMPTZ NOT NULL,
  opened_at                TIMESTAMPTZ,
  created_at               TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE (league_id, season_id, user_id, week)
);

CREATE INDEX idx_weekly_packs_user   ON public.weekly_packs (user_id);
CREATE INDEX idx_weekly_packs_league ON public.weekly_packs (league_id);
CREATE INDEX idx_weekly_packs_week   ON public.weekly_packs (season_id, week);

-- RLS: users see and update only their own packs
ALTER TABLE public.weekly_packs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users can read their own packs"
  ON public.weekly_packs FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "users can update their own packs"
  ON public.weekly_packs FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Extend leagues with an optional roster-slots config
-- ---------------------------------------------------------------------------
ALTER TABLE public.leagues
  ADD COLUMN IF NOT EXISTS roster_slots JSONB DEFAULT '[]';

-- ---------------------------------------------------------------------------
-- Extend draft_picks to support pack acquisitions and soft-drops
--
-- source: 'draft' (original pick) | 'pack' (added from weekly pack)
-- dropped_at: null = on roster; set = dropped
-- ---------------------------------------------------------------------------
ALTER TABLE public.draft_picks
  ADD COLUMN IF NOT EXISTS source     TEXT DEFAULT 'draft';

ALTER TABLE public.draft_picks
  ADD COLUMN IF NOT EXISTS dropped_at TIMESTAMPTZ;

-- Fix the unique index: only enforce uniqueness for drafted picks.
-- Pack picks all use pick_number=0 and must not conflict.
DROP INDEX IF EXISTS draft_picks_draft_pick_num_idx;
CREATE UNIQUE INDEX draft_picks_draft_pick_num_idx
  ON public.draft_picks (draft_id, pick_number)
  WHERE (source IS NULL OR source = 'draft');

-- Allow team owners to soft-drop their own players (set dropped_at)
CREATE POLICY "team can drop their own players"
  ON public.draft_picks FOR UPDATE
  USING  (team_user_id = auth.uid())
  WITH CHECK (team_user_id = auth.uid());
